#!/bin/sh
ssh ubuntu@ec2-3-22-164-151.us-east-2.compute.amazonaws.com
cd ~/node-hello
git clone https://github.com/ZafarIqbal777/node-hello.git
curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
. ~/.nvm/nvm.sh
nvm install v15.14.0
npm install
npm install -g nodemon pm2
pm2 restart ecosystem.config.js